services:
  website:
    image: itsmauvee/ci-cdtesting
    ports:
      - 8080:8080

  watchtower:
    image: nickfedor/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    environment:
    - WATCHTOWER_POLL_INTERVAL=2    # check every 30 seconds